import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '../components/footer'
import Navigation from '../components/navigation'
import './globals.css'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className='dark'>
      <body className={inter.className}>
        <Providers>
          <Navigation />
          <main className='h-screen-minus-footer flex flex-col pt-[72px] w-full max-w-[1440px] mx-auto'>
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
