import { productService } from '@/services/product-service'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { Inter } from 'next/font/google'
import { authOptions } from './auth/authOptions'
import './globals.css'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions)
  const userId = session?.user?.id

  const products = await productService.getProductsAction({ skip: 0, userId })
  const totalProducts = await productService.getTotalProductsAction()

  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers products={products} totalProducts={totalProducts}>
          {children}
        </Providers>
      </body>
    </html>
  )
}
